export const katakanaDummyData = [
    { katakana: "ア", english: "a" },
    { katakana: "イ", english: "i" },
    { katakana: "ウ", english: "u" },
    { katakana: "エ", english: "e" },
    { katakana: "オ", english: "o" },
    { katakana: "カ", english: "ka" },
    { katakana: "キ", english: "ki" },
    { katakana: "ク", english: "ku" },
    { katakana: "ケ", english: "ke" },
    { katakana: "コ", english: "ko" },
    { katakana: "サ", english: "sa" },
    { katakana: "シ", english: "shi" },
    { katakana: "ス", english: "su" },
    { katakana: "セ", english: "se" },
    { katakana: "ソ", english: "so" },
    { katakana: "タ", english: "ta" },
    { katakana: "チ", english: "chi" },
    { katakana: "ツ", english: "tsu" },
    { katakana: "テ", english: "te" },
    { katakana: "ト", english: "to" },
  ];
